<?php
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "	<head>\n";
echo "		<title>CARIT</title>\n";
echo "	<link rel=\"stylesheet\" href=\"styles.css\">	\n";
echo "	</head>\n";
echo "	\n";
echo "	<body style=\"background-color:#ECD1CB\">\n";
echo "\n";
echo "\n";
echo "	<center><h1>Center for Research in Information Technology </h1></center>\n";
echo "	\n";
echo "	\n";
echo "	<center><img src=\"images/CARITlogo.jpg\" alt=\"CARITLogo\"></center>\n";
echo "	<center>\n";
echo "		<h2>Welcome to the Homepage of CARIT</h2>\n";
echo "		</center>\n";
echo "		\n";
echo "		\n";
echo "		<br>\n";
echo "<center>\n";
echo "<h6>\n";
echo "<table style=\"width:80%\">\n";
echo "  <tr>\n";
echo "  <th><a href=\"index.php\">Home Page</a></th>\n";
echo "	<th><a href=\"aboutus.php\">About Us</a></th>\n";
echo "  <th><a href=\"facultypage.php\">Faculty Page</a> </th>\n";
echo "	<th><a href=\"resources.php\">Resources</a> </th>\n";
echo "	<th><a href=\"appform.php\">Application Form</a> </th>\n";
echo "	<th><a href=\"programs.php\">Programs</a> </th>\n";
echo "	<th><a href=\"services.php\">Services</a> </th>\n";

echo "	\n";
echo "	\n";
echo "  </tr>\n";
echo "\n";
echo "</table>\n";
echo "</h6>\n";
echo "</center>\n";
echo "		\n";
echo "<div>\n";
echo "		<p> This is a very well organized IT training company. We have tremendous expert trainers to serve you in different\n";
echo "level. They can help you to learn different language like Java, Python, C C++ etc.Care IT Services is an Information \n";
echo "Technology Products & Services Company that provides Software Products, \n";
echo "Contingent IT Staffing, Custom Software Development and IT Solutions.</p>\n";
echo "\n";
echo "<p>\n";
echo "Through offices in the United States and Offshore, \n";
echo "we provide IT products & services to Federal and State Governments, \n";
echo "to Fortune more Companies, and to emerging growth businesses. \n";
echo "We support such business sectors as Financial Services, Banking, \n";
echo "Insurance, Retail, Healthcare, Manufacturing, Telecom, Pharmaceuticals, Oil & Gas, \n";
echo "and Transportation & Other Industries. </p>\n";
echo "<br>\n";
echo "</div>\n";
echo "<div>\n";
echo "   <h3> <p> Our Mission and Vision:</p></h3>\n";
echo "	  <ul>\n";
echo "	      <li>Provide the best qualilty.</li> \n";
echo "          <li>Flexible schedule.</li>\n";
echo "          <li>Affordable tuition fees.</li>\n";
echo "		<li>Job placement.</li>\n";
echo "		</ul>\n";
echo "		\n";
echo "</div>\n";
echo "\n";
echo "<div>\n";
echo "  <h3> <p> Our Success Rate</p></h3>\n";
echo "<table border=\"1\" style=\"width:50%\">\n";
echo "  <tr>\n";
echo "    <th> Year</th>\n";
echo "	<th> Admitted</th>\n";
echo "	<th> Pass rate</th>\n";
echo "	<th> Placement Rate</th>\n";
echo "  </tr>\n";
echo " <tr>\n";
echo "  <td> 2015 </td>\n";
echo "	<td> 512 </td>\n";
echo "	<td> 80% </td>\n";
echo "	<td> 90% </td>\n";
echo " </tr>	\n";
echo "  \n";
echo " <tr>\n";
echo "  <td> 2016 </td>\n";
echo "	<td> 571 </td>\n";
echo "	<td> 70% </td>\n";
echo "	<td> 80% </td>\n";
echo " </tr>	\n";
echo "  \n";
echo "<tr>\n";
echo "  <td> 2017 </td>\n";
echo "	<td> 809 </td>\n";
echo "	<td> 83% </td>\n";
echo "	<td> 85% </td>\n";
echo " </tr>	\n";
echo "  \n";
echo "  <tr>\n";
echo "  <td> 2018 </td>\n";
echo "	<td> 1088 </td>\n";
echo "	<td> 77% </td>\n";
echo "	<td> 90% </td>\n";
echo " </tr>	\n";
echo "  <tr>\n";
echo "  <td> 2019 </td>\n";
echo "	<td> 876 </td>\n";
echo "	<td> 85% </td>\n";
echo "	<td> 98% </td>\n";
echo " </tr>	\n";
echo "  \n";
echo "</table>\n";
echo "	\n";
echo "	</div>\n";
echo " 	   \n";
echo "	   <div>\n";
echo "		<h2> DON'T MISS OUR NEW YEARS SAVINGS HURRY BEFORE THEY ARE GONE</h2>\n";
echo "		<br>\n";
echo "		<br>\n";
echo "		<h1>_____________________________________________________________________________________________</h1>\n";
echo "		\n";
echo "		<h1>NEWS HEADLINES</h1>\n";
echo "		<h2><p style= \"background-color:gray;\">Corona Virus is getting serious all over the world.</p></h2>\n";
echo "		<br>\n";
echo "		\n";
echo "		<br>\n";
echo "		<br>\n";
echo "</div>		\n";
echo "<br>\n";
echo "<center>\n";
echo "<h6>\n";
echo "<table style=\"width:80%\">\n";
echo "  <tr>\n";
echo "  <th><a href=\"index.php\">Home Page</a></th>\n";
echo "	<th><a href=\"aboutus.php\">About Us</a></th>\n";
echo "    <th><a href=\"facultypage.php\">Faculty Page</a> </th>\n";
echo "	<th><a href=\"resources.php\">Resources</a> </th>\n";
echo "	<th><a href=\"appform.php\">Application Form</a> </th>\n";
echo "	<th><a href=\"programs.php\">Programs</a> </th>\n";
echo "	\n";
echo "	<th><a href=\"services.php\">Services</a> </th>\n";

echo "	\n";
echo "	\n";
echo "  </tr>\n";
echo "\n";
echo "</table>\n";
echo "</h6>\n";
echo "</center>\n";
echo "\n";
echo "	</center>\n";
echo "		<br>\n";
echo "		<br>\n";
echo "	<h4>\n";
echo "		This is a class project of the course <a href= \"http://it5443.azurewebsites.net/\"> MSIT 5443 at KSU</a>\n";
echo "		</h4>\n";
echo "			\n";
echo "		\n";
echo "	<div>\n";
echo "		<br>\n";
echo "		<br>\n";
echo "		<h5>Address: 1005 Paradise Rd, Atlanata, GA 30339. Phone: 404-345-6789</h5>\n";
echo "		<br>\n";
echo "\n";
echo "	\n";
echo "	</div>	\n";
echo "\n";
echo "\n";
echo "	</body>\n";
echo "</html>\n";
?>