<?php
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "	<head>\n";
echo "		<title>CARIT</title>\n";
echo "	<link rel=\"stylesheet\" href=\"styles.css\">	\n";
echo "	</head>\n";
echo "	\n";
echo "	<body style=\"background-color:#ECD1CB\">\n";

echo "\n";
echo "\n";
echo "	<center><h1>Welcome to the  CARIT </h1></center>\n";
echo "	\n";
echo "	\n";
echo "	<center><img src=\"images/CARITlogo.jpg\" alt=\"CARITLogo\"></center>\n";
echo "	<center>\n";
echo "		<h2>CARIT About Us and Faculty Page</h2>\n";
echo "		</center>\n";
echo "		\n";
echo "<center>\n";
echo "<h6>\n";
echo "<table style=\"width:80%\">\n";
echo "  <tr>\n";
echo "    <th><a href=\"index.php\">Home Page</a></th>\n";
echo "	<th><a href=\"aboutus.php\">About Us</a></th>\n";
echo "    <th><a href=\"facultypage.php\">Faculty Page</a> </th>\n";
echo "	<th><a href=\"resources.php\">Resources</a> </th>\n";
echo "	<th><a href=\"appform.php\">Application Form</a> </th>\n";
echo "	<th><a href=\"programs.php\">Programs</a> </th>\n";
echo " \n";
echo "	<th><a href=\"services.php\">Services</a> </th>\n";

echo "	\n";
echo "	\n";
echo "  </tr>\n";
echo "\n";
echo "</table>\n";
echo "</h6>\n";
echo "</center>\n";
echo "		\n";
echo "<div> 		\n";
echo "<h1>About Us</h1>\n";
echo "		\n";
echo "CARIT is an excellent and trusted IT Solution and Services company. It is a well-known IT company located in Atlana, GA, United States.\n";
echo "		<center>\n";
echo "</div>\n";
echo "\n";
echo "<div>\n";
echo "		<h2>CARIT Faculty Members </h2>\n";
echo "	</center>\n";
echo "	\n";
echo "<h2>Dr. Lei Li</h2>\n";
echo "<br>\n";
echo "<img src=\"images/LeiLi.jpg\" alt=\"Dr. Lei Li\" \n";
echo "					style=\"width:200px;height:200px;\">\n";
echo "<br> <br>\n";
echo "\n";
echo "<b> Position: </b> KSU Professor & MSIT Coordinator \n";
echo "\n";
echo "<br>";
echo "<b>Phone: </b>(470) 578-3915\n";
echo "<br>";
echo "<b>Email: </b>lli13@kennesaw.edu\n";
echo "<br>";
echo "<b>Location:</b> J 364\n";
echo "<a href= \"https://ccse.kennesaw.edu/it/faculty-staff.php\">Web site</a\n";
echo "<br>\n";
echo "<h4>Research Interests:</h4> Social Media Data Analytics, Information Security, Web Information Management, IT Education\n";
echo "\n";
echo "<h2>Dr. Linh Li</h2>\n";
echo "<br>\n";
echo "<img src=\"images/Linhli.jpg\" alt=\"Dr. Linh Li\" \n";
echo "					style=\"width:200px;height:200px;\">\n";
echo "<br> <br>\n";
echo "\n";
echo "<b> Position: </b> Limited Term Assistant Professor of Information Technology\n";
echo "\n";
echo "<br>";
echo "<b>Phone: </b>(470) 578-6099\n";
echo "<br>";
echo "<b>Email: </b>lle13@kennesaw.edu\n";
echo "<br>";
echo "<b>Location:</b> J 366\n";
echo "<a href= \"https://ccse.kennesaw.edu/it/faculty-staff.php\">Web site</a\n";
echo "<br>\n";
echo "<h4>Research Interests:</h4> IT, Software Design and Development\n";
echo "\n";
echo "\n";
echo "<h2>Dr. Svetlana Peltsverger</h2>\n";
echo "<br>\n";
echo "<img src=\"images/Svetlana.jpg\" alt=\"Dr. Svetlana Peltsverger\" \n";
echo "					style=\"width:200px;height:200px;\">\n";
echo "<br> <br>\n";
echo "\n";
echo "\n";
echo "<b> Position: </b> Interim Associate Dean of the College of Computing and Software Engineering\n";
echo "\n";
echo "<br>";
echo "<b>Phone: </b>(470) 578-3813\n";
echo "<br>";
echo "<b>Email: </b>speltsve@kennesaw.edu\n";
echo "<br>";
echo "<b>Location:</b> J 366\n";
echo "<a href= \"https://ccse.kennesaw.edu/it/faculty-staff.php\">Web site</a\n";
echo "<br>\n";
echo "		\n";
echo "<h4>Research Interests:</h4> Security, Databases, Distributed computing and Privacy\n";
echo "\n";
echo "\n";
echo "\n";
echo "</div>\n";
echo "	\n";
echo "\n";
echo "<div>\n";
echo "   <h3> <p> Our Mission and Vision:</p></h3>\n";
echo "	  <ul>\n";
echo "	      <li>Provide the best qualilty.</li> \n";
echo "          <li>Flexible schedule.</li>\n";
echo "          <li>Affordable tuition fees.</li>\n";
echo "		<li>Job placement.</li>\n";
echo "		</ul>\n";
echo "		\n";
echo " 	   </div>\n";
echo "<div>\n";
echo "\n";
echo "		<br>\n";
echo "		<br>\n";
echo "		<h1>_____________________________________________________________________________________________</h1>\n";
echo "		\n";
echo "		<h1>NEWS HEADLINES</h1>\n";
echo "		<h2><p style= \"background-color:gray;\">Corona Virus is getting serious all over the world.</p></h2>\n";
echo "		<br>\n";
echo "		\n";
echo "		<br>\n";
echo "		<br>\n";
echo "		<br>\n";
echo "		\n";
echo "</div>\n";
echo "\n";
echo "		<br>\n";
echo "		<br>\n";
echo "		<br>\n";
echo "		\n";
echo "		<br>\n";
echo "	</center>\n";
echo "		<br>\n";
echo "		<br>\n";
echo "		<h4>\n";
echo "		This is a class project of the course <a href= \"http://it5443.azurewebsites.net/\"> MSIT 5443 at KSU</a>\n";
echo "		</h4>\n";
echo "		\n";
echo "		\n";
echo "			<div>\n";
echo "		<br>\n";
echo "		<br>\n";
echo "		<h5>Address: 1005 Paradise Rd, Atlanata, GA 30339. Phone: 404-345-6789</h5>\n";
echo "		<br>\n";
echo "\n";
echo "	\n";
echo "	</div>	\n";
echo "\n";
echo "		<center>\n";
echo "<h6>\n";
echo "<table style=\"width:80%\">\n";
echo "  <tr>\n";
echo "    <th><a href=\"index.php\">Home Page</a></th>\n";
echo "	<th><a href=\"aboutus.php\">About Us</a></th>\n";
echo "    <th><a href=\"facultypage.php\">Faculty Page</a> </th>\n";
echo "	<th><a href=\"resources.php\">Resources</a> </th>\n";
echo "	<th><a href=\"appform.php\">Application Form</a> </th>\n";
echo "	<th><a href=\"programs.php\">Programs</a> </th>\n";
echo " \n";
echo "	<th><a href=\"services.php\">Services</a> </th>\n";

echo "	\n";
echo "	\n";
echo "  </tr>\n";
echo "\n";
echo "</table>\n";
echo "</h6>\n";
echo "</center>\n";
echo "\n";
echo "\n";
echo "\n";
echo "	</body>\n";
echo "</html>\n";
?>